### ISSUE TITLE
Global Changelog

### ISSUE THREAD

**Issue by nothingismagick** [jbolda/covector#119]
For monorepos it can be tedious (yes I am lazy) to descend through each folder and find the CHANGELOG.md file. Would be nice to also have a root-level CHANGELOG separated by package.

**Comment by jbolda** [comment]
One of the reasons to put the changelog in each folder is then that can be published along with the package so I imagine you may want both. Another possibility is linking to the changelogs in the readme in the monorepo root.

**Comment by nothingismagick** [comment]
Yeah both would be amazing.

**Comment by nothingismagick** [comment]
But a link to them would probably suffice for those who don't have such an awesome page like this:

https://tauri.studio/release-notes

**Comment by jbolda** [comment]
I think rather than duplicating the same content everywhere, we recommend the user includes links to each package changelog in the root readme or in a static root changelog.

In the use case where the root is being published and we want a changelog that contains everything, then we recommend the user adds that as a "package". A possible use case would be when publishing a docker image for the collection of packages+services in a repo.
