### ISSUE TITLE
Dry run flag doesn't seem to work?

### ISSUE THREAD

**Issue by minkimcello** [jbolda/covector#167]
Could I get some clarification on how `--dry-run` is meant to function?

I saw this:
```js
if (
  typeof pubCommand === "object" &&
  pubCommand.dryRunCommand === false
) {
  runningCommand.command = pubCommand.command;
  runningCommand.shouldRunCommand = !dryRun;
} else if (typeof pubCommand === "object") {
  // dryRunCommand will either be a !string (false) or !undefined (true) or !true (false)
  if (pubCommand.dryRunCommand === true) {
    runningCommand.command = pubCommand.command;
    runningCommand.shouldRunCommand = true;
  } else if (typeof pubCommand.dryRunCommand === "string" && dryRun) {
    runningCommand.command = pubCommand.dryRunCommand;
    runningCommand.shouldRunCommand = true;
  } else {
    runningCommand.command = pubCommand.command;
    runningCommand.shouldRunCommand = !dryRun;
  }
} else {
  runningCommand.command = pubCommand;
  runningCommand.shouldRunCommand = !dryRun;
}
```
And thought, "okay I should ask Jacob".

My assumption was that it's supposed to just console log out the command. For instance, if I do `yarn covector publish --dry-run` it will show me `npm publish --access public` on the console but not actually run the command. But when I run `yarn covector publish --dry-run` it will actually attempt to publish to the registry.

Also, what's the purpose of `config.json`'s `pkgManagers.javascript.publish.dryRunCommand`?

**Comment by jbolda** [comment]
Yea, that could really use some help from Typescript and splitting the code up or something. It was organic growth to improve production and debug output, but the code got kind of ugly there. Dry run mode shouldn't ever do any publishing so that would be surprising if it was happening.

There are a few options for the dry run in regards to the command. If your command is purely a string, `npm publish`, it will just log that string out instead. If you give it an object, you can optionally pass a `dryRunCommand` as `true` and it will run the command even in dry run mode. Additionally you can give it a string to run _instead_ in dry run mode.

Example of a string passed to `dryRunCommand`:
```json
  {
    "command": "cargo publish --no-verify",
    "dryRunCommand": "cargo publish --no-verify --dry-run --allow-dirty",
    "pipe": true
  },
```

Example of `true`:
```json
{
  "command": "cargo audit ${ process.env.CARGO_AUDIT_OPTIONS || '' }",
  "dryRunCommand": true,
  "runFromRoot": true,
  "pipe": true
},
```

We wanted these specifically for use in Tauri recreating workflows we had previously. Another one of those advanced use cases that has yet to be documented. You can specify these either on `pkgManager` or on a specific `package` where the objects get merged like `{...pkgManager, ...package}` for each package.
