### ISSUE TITLE
Renaming changes

### ISSUE THREAD

**Issue by minkimcello** [jbolda/covector#168]
While reading through the README, the biggest hurdle I found was understanding what `changes` meant. Once you _know_ it's pretty obvious but otherwise it can be pretty confusing.

I think the obvious choice would be to change it to `.covector/`. So then we can say "if there are no covectors" or "you need to create a new covector", it's pretty clear that we're not talking about the tool itself but the markdown files.

Also, on that subject (and also so I don't spam too many issues), I think it would be helpful to have a `yarn covector generate|create` command to create an empty template. I know some people like to type these markdown files out themselves but with `changesets` I only use the CLI command to generate the markdown files. Thoughts?

**Comment by jbolda** [comment]
Sounds like something we do need to address. I wonder though if this is more a documentation issue and less a terminology issue? I kind of like `.changes` as a folder name since it doesn't require someone having knowledge of covector to guess what that folder might contain.

No worries about creating new issues. A helper to create a markdown file is high on my priority list as well; we definitely need it. I was thinking of calling it `covector add`, but makes sense to me to open up a new issue and fill in thoughts further.
